// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto

package com.luna.console.webserver.protoClass;

public final class GameProtocol {
  private GameProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 session = 1;
    /**
     * <code>optional uint32 session = 1;</code>
     */
    boolean hasSession();
    /**
     * <code>optional uint32 session = 1;</code>
     */
    int getSession();

    // optional uint32 action = 2;
    /**
     * <code>optional uint32 action = 2;</code>
     *
     * <pre>
     * 0-initializeGame, 1-playGame
     * </pre>
     */
    boolean hasAction();
    /**
     * <code>optional uint32 action = 2;</code>
     *
     * <pre>
     * 0-initializeGame, 1-playGame
     * </pre>
     */
    int getAction();

    // optional string game = 3;
    /**
     * <code>optional string game = 3;</code>
     */
    boolean hasGame();
    /**
     * <code>optional string game = 3;</code>
     */
    java.lang.String getGame();
    /**
     * <code>optional string game = 3;</code>
     */
    com.google.protobuf.ByteString
        getGameBytes();

    // optional bytes data = 4;
    /**
     * <code>optional bytes data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.luna.console.webserver.proto.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              session_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              action_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              game_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luna.console.webserver.protoClass.GameProtocol.Request.class, com.luna.console.webserver.protoClass.GameProtocol.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 session = 1;
    public static final int SESSION_FIELD_NUMBER = 1;
    private int session_;
    /**
     * <code>optional uint32 session = 1;</code>
     */
    public boolean hasSession() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 session = 1;</code>
     */
    public int getSession() {
      return session_;
    }

    // optional uint32 action = 2;
    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <code>optional uint32 action = 2;</code>
     *
     * <pre>
     * 0-initializeGame, 1-playGame
     * </pre>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 action = 2;</code>
     *
     * <pre>
     * 0-initializeGame, 1-playGame
     * </pre>
     */
    public int getAction() {
      return action_;
    }

    // optional string game = 3;
    public static final int GAME_FIELD_NUMBER = 3;
    private java.lang.Object game_;
    /**
     * <code>optional string game = 3;</code>
     */
    public boolean hasGame() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string game = 3;</code>
     */
    public java.lang.String getGame() {
      java.lang.Object ref = game_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          game_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string game = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGameBytes() {
      java.lang.Object ref = game_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        game_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      session_ = 0;
      action_ = 0;
      game_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, session_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, action_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getGameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, session_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, action_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getGameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luna.console.webserver.protoClass.GameProtocol.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.luna.console.webserver.proto.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luna.console.webserver.protoClass.GameProtocol.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luna.console.webserver.protoClass.GameProtocol.Request.class, com.luna.console.webserver.protoClass.GameProtocol.Request.Builder.class);
      }

      // Construct using com.luna.console.webserver.protoClass.GameProtocol.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        session_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        game_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Request_descriptor;
      }

      public com.luna.console.webserver.protoClass.GameProtocol.Request getDefaultInstanceForType() {
        return com.luna.console.webserver.protoClass.GameProtocol.Request.getDefaultInstance();
      }

      public com.luna.console.webserver.protoClass.GameProtocol.Request build() {
        com.luna.console.webserver.protoClass.GameProtocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luna.console.webserver.protoClass.GameProtocol.Request buildPartial() {
        com.luna.console.webserver.protoClass.GameProtocol.Request result = new com.luna.console.webserver.protoClass.GameProtocol.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.session_ = session_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.game_ = game_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luna.console.webserver.protoClass.GameProtocol.Request) {
          return mergeFrom((com.luna.console.webserver.protoClass.GameProtocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luna.console.webserver.protoClass.GameProtocol.Request other) {
        if (other == com.luna.console.webserver.protoClass.GameProtocol.Request.getDefaultInstance()) return this;
        if (other.hasSession()) {
          setSession(other.getSession());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasGame()) {
          bitField0_ |= 0x00000004;
          game_ = other.game_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luna.console.webserver.protoClass.GameProtocol.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luna.console.webserver.protoClass.GameProtocol.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 session = 1;
      private int session_ ;
      /**
       * <code>optional uint32 session = 1;</code>
       */
      public boolean hasSession() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 session = 1;</code>
       */
      public int getSession() {
        return session_;
      }
      /**
       * <code>optional uint32 session = 1;</code>
       */
      public Builder setSession(int value) {
        bitField0_ |= 0x00000001;
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 session = 1;</code>
       */
      public Builder clearSession() {
        bitField0_ = (bitField0_ & ~0x00000001);
        session_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 action = 2;
      private int action_ ;
      /**
       * <code>optional uint32 action = 2;</code>
       *
       * <pre>
       * 0-initializeGame, 1-playGame
       * </pre>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 action = 2;</code>
       *
       * <pre>
       * 0-initializeGame, 1-playGame
       * </pre>
       */
      public int getAction() {
        return action_;
      }
      /**
       * <code>optional uint32 action = 2;</code>
       *
       * <pre>
       * 0-initializeGame, 1-playGame
       * </pre>
       */
      public Builder setAction(int value) {
        bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 action = 2;</code>
       *
       * <pre>
       * 0-initializeGame, 1-playGame
       * </pre>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = 0;
        onChanged();
        return this;
      }

      // optional string game = 3;
      private java.lang.Object game_ = "";
      /**
       * <code>optional string game = 3;</code>
       */
      public boolean hasGame() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public java.lang.String getGame() {
        java.lang.Object ref = game_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          game_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGameBytes() {
        java.lang.Object ref = game_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          game_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public Builder setGame(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        game_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public Builder clearGame() {
        bitField0_ = (bitField0_ & ~0x00000004);
        game_ = getDefaultInstance().getGame();
        onChanged();
        return this;
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public Builder setGameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        game_ = value;
        onChanged();
        return this;
      }

      // optional bytes data = 4;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.luna.console.webserver.proto.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.luna.console.webserver.proto.Request)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional double balance = 1;
    /**
     * <code>optional double balance = 1;</code>
     */
    boolean hasBalance();
    /**
     * <code>optional double balance = 1;</code>
     */
    double getBalance();

    // optional uint32 action = 2;
    /**
     * <code>optional uint32 action = 2;</code>
     */
    boolean hasAction();
    /**
     * <code>optional uint32 action = 2;</code>
     */
    int getAction();

    // optional string game = 3;
    /**
     * <code>optional string game = 3;</code>
     */
    boolean hasGame();
    /**
     * <code>optional string game = 3;</code>
     */
    java.lang.String getGame();
    /**
     * <code>optional string game = 3;</code>
     */
    com.google.protobuf.ByteString
        getGameBytes();

    // optional bytes data = 4;
    /**
     * <code>optional bytes data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.luna.console.webserver.proto.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              balance_ = input.readDouble();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              action_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              game_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luna.console.webserver.protoClass.GameProtocol.Response.class, com.luna.console.webserver.protoClass.GameProtocol.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional double balance = 1;
    public static final int BALANCE_FIELD_NUMBER = 1;
    private double balance_;
    /**
     * <code>optional double balance = 1;</code>
     */
    public boolean hasBalance() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double balance = 1;</code>
     */
    public double getBalance() {
      return balance_;
    }

    // optional uint32 action = 2;
    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <code>optional uint32 action = 2;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 action = 2;</code>
     */
    public int getAction() {
      return action_;
    }

    // optional string game = 3;
    public static final int GAME_FIELD_NUMBER = 3;
    private java.lang.Object game_;
    /**
     * <code>optional string game = 3;</code>
     */
    public boolean hasGame() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string game = 3;</code>
     */
    public java.lang.String getGame() {
      java.lang.Object ref = game_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          game_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string game = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGameBytes() {
      java.lang.Object ref = game_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        game_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      balance_ = 0D;
      action_ = 0;
      game_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, balance_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, action_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getGameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, balance_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, action_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getGameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luna.console.webserver.protoClass.GameProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luna.console.webserver.protoClass.GameProtocol.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.luna.console.webserver.proto.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luna.console.webserver.protoClass.GameProtocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luna.console.webserver.protoClass.GameProtocol.Response.class, com.luna.console.webserver.protoClass.GameProtocol.Response.Builder.class);
      }

      // Construct using com.luna.console.webserver.protoClass.GameProtocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        balance_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        game_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luna.console.webserver.protoClass.GameProtocol.internal_static_com_luna_console_webserver_proto_Response_descriptor;
      }

      public com.luna.console.webserver.protoClass.GameProtocol.Response getDefaultInstanceForType() {
        return com.luna.console.webserver.protoClass.GameProtocol.Response.getDefaultInstance();
      }

      public com.luna.console.webserver.protoClass.GameProtocol.Response build() {
        com.luna.console.webserver.protoClass.GameProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luna.console.webserver.protoClass.GameProtocol.Response buildPartial() {
        com.luna.console.webserver.protoClass.GameProtocol.Response result = new com.luna.console.webserver.protoClass.GameProtocol.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.balance_ = balance_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.game_ = game_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luna.console.webserver.protoClass.GameProtocol.Response) {
          return mergeFrom((com.luna.console.webserver.protoClass.GameProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luna.console.webserver.protoClass.GameProtocol.Response other) {
        if (other == com.luna.console.webserver.protoClass.GameProtocol.Response.getDefaultInstance()) return this;
        if (other.hasBalance()) {
          setBalance(other.getBalance());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasGame()) {
          bitField0_ |= 0x00000004;
          game_ = other.game_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luna.console.webserver.protoClass.GameProtocol.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luna.console.webserver.protoClass.GameProtocol.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional double balance = 1;
      private double balance_ ;
      /**
       * <code>optional double balance = 1;</code>
       */
      public boolean hasBalance() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double balance = 1;</code>
       */
      public double getBalance() {
        return balance_;
      }
      /**
       * <code>optional double balance = 1;</code>
       */
      public Builder setBalance(double value) {
        bitField0_ |= 0x00000001;
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double balance = 1;</code>
       */
      public Builder clearBalance() {
        bitField0_ = (bitField0_ & ~0x00000001);
        balance_ = 0D;
        onChanged();
        return this;
      }

      // optional uint32 action = 2;
      private int action_ ;
      /**
       * <code>optional uint32 action = 2;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 action = 2;</code>
       */
      public int getAction() {
        return action_;
      }
      /**
       * <code>optional uint32 action = 2;</code>
       */
      public Builder setAction(int value) {
        bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 action = 2;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = 0;
        onChanged();
        return this;
      }

      // optional string game = 3;
      private java.lang.Object game_ = "";
      /**
       * <code>optional string game = 3;</code>
       */
      public boolean hasGame() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public java.lang.String getGame() {
        java.lang.Object ref = game_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          game_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGameBytes() {
        java.lang.Object ref = game_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          game_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public Builder setGame(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        game_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public Builder clearGame() {
        bitField0_ = (bitField0_ & ~0x00000004);
        game_ = getDefaultInstance().getGame();
        onChanged();
        return this;
      }
      /**
       * <code>optional string game = 3;</code>
       */
      public Builder setGameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        game_ = value;
        onChanged();
        return this;
      }

      // optional bytes data = 4;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.luna.console.webserver.proto.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.luna.console.webserver.proto.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_luna_console_webserver_proto_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_luna_console_webserver_proto_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_luna_console_webserver_proto_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_luna_console_webserver_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGame.proto\022 com.luna.console.webserver" +
      ".proto\"F\n\007Request\022\017\n\007session\030\001 \001(\r\022\016\n\006ac" +
      "tion\030\002 \001(\r\022\014\n\004game\030\003 \001(\t\022\014\n\004data\030\004 \001(\014\"G" +
      "\n\010Response\022\017\n\007balance\030\001 \001(\001\022\016\n\006action\030\002 " +
      "\001(\r\022\014\n\004game\030\003 \001(\t\022\014\n\004data\030\004 \001(\014B5\n%com.l" +
      "una.console.webserver.protoClassB\014GamePr" +
      "otocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_luna_console_webserver_proto_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_luna_console_webserver_proto_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_luna_console_webserver_proto_Request_descriptor,
              new java.lang.String[] { "Session", "Action", "Game", "Data", });
          internal_static_com_luna_console_webserver_proto_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_luna_console_webserver_proto_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_luna_console_webserver_proto_Response_descriptor,
              new java.lang.String[] { "Balance", "Action", "Game", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
